### ISSUE TITLE
GradCAM

### ISSUE THREAD

**Issue by qbeer** [ahmdtaha/constrained_attention_filter#1]
Hey there,

 reading your paper I wish to implement some visualization techniques for image embeddings based on your description. I wish to implement GradCAM as you stated for features ***y***. Well, I have a problem since I have not found a standard solution for this particular problem. Speaking in derivatives if my features have 128 dimensions while a ResNet activation output maps before global average pooling can be [A] = (4, 4, 2048) in shape. So far so good, however, the derivatives infer [dydA] = (128, 4, 4, 2048) and we should mean it alongside the **w, h** (4-4) dimensions, I'll call this ***dA***.  Moving on to the results of weighing the original activation maps with these parameters acquired by derivation we get an output map ***M*** (same notation as in your paper) for the visualization map. My - so to say - problem is that this results in a 3-dimensional tensor of shape (128, 4, 4). Of course, I could upsample this in the last two dimensions to the input size but how did you deal with that this method results in a 'feature' activation map in each output dimension? Do I sum it? Do I mean it? Do I take the max activations? I'm looking forward to your answer until then I might take one of the paths described in the previous sentence and move on to implementing L2-CAF. Thanks in advance.

Alex

**Comment by ahmdtaha** [comment]
Hi Alex,

GradCAM does not work with feature embedding networks for the problem you have pointed out.
I used tf.gradients to get compute the derivative with respect to the conv_layer. When given a feature vector y\in R^128, tf.gradient(y,conv_layer) => tf.gradient(sum(y),conv_layer) as pointed out in [1].
This TF function returns the gradient of the sum. This way every dimension contributes to the gradient.
I hope this helps.

[1] [https://github.com/tensorflow/tensorflow/issues/4897#issuecomment-311777508](https://github.com/tensorflow/tensorflow/issues/4897#issuecomment-311777508)

Thanks

**Comment by qbeer** [comment]
Summing it is. Thanks for the quick reply, it was indeed helpful.

**Comment by ahmdtaha** [comment]
Make sure to take the abs, i.e., Grad-CAM-abs. For feature embedding networks, this is a considerably better baseline than the vanilla Grad-CAM with RELU
